### ISSUE TITLE
[feature request] Prompt asking for derivation path

### ISSUE THREAD

**Issue by Janaka-Steph** [DigixGlobal/sigmate#1]
Hello,

After investigating I found that different Ethereum project are using different derivation paths. Sigmate / eth-lightwallet use the "Consensys" derivation path "m/0'/0'/0'" by default, whereas Metamask and Testrpc use the BIP44 derivation path "m/44'/60'/0'/0". 
So I would like to request a feature. When running `sigmate keystore`, I would like to be able to choose between these two or being able to enter the derivation path I want. 

Do you think it is relevant ? 
Thank you for your great work.

**Comment by IstoraMandiri** [comment]
Yes, good idea. Thanks for this. I'll add this feature. 👍

**Comment by IstoraMandiri** [comment]
fixed in 3.0.4
